import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/navbar/page";

export const metadata: Metadata = {
  title: "Note Easy",
  description: "Generated by Jayping",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white h-screen overflow-y-auto">
        <div className="fixed top-0 left-0 w-full z-10">
          <Nav />
        </div>
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
